server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://todoliutikas.database.windows.net:1433;database=ToDoApi;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: MatLiu@todoliutikas
    password: slaptazodis5%
  jpa:
    hibernate:
      ddl-auto: update